DROP TABLE IF EXISTS "User" CASCADE ;
DROP TABLE IF EXISTS Forum CASCADE ;
DROP TABLE IF EXISTS Thread CASCADE ;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS UserVoteThread;

CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE IF NOT EXISTS "User" (
  id SERIAL PRIMARY KEY,
  nickname CITEXT COLLATE "ucs_basic" UNIQUE NOT NULL,
  fullname VARCHAR(256) NOT NULL,
  about TEXT,
  email CITEXT COLLATE "ucs_basic" UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Forum (
  id SERIAL PRIMARY KEY,
  title VARCHAR(256),
  "user" CITEXT COLLATE "ucs_basic" NOT NULL REFERENCES "User" (nickname) ON DELETE CASCADE,
  slug CITEXT COLLATE "ucs_basic" NOT NULL UNIQUE,
  posts INTEGER DEFAULT 0,
  threads INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Thread (
  id SERIAL PRIMARY KEY,
  title VARCHAR(256),
  author CITEXT COLLATE "ucs_basic" NOT NULL REFERENCES "User" (nickname) ON DELETE CASCADE,
  forum CITEXT NOT NULL REFERENCES Forum (slug) ON DELETE CASCADE,
  message TEXT,
  votes INTEGER DEFAULT 0,
  slug CITEXT UNIQUE,
  created TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS UserVoteThread (
  id SERIAL PRIMARY KEY ,
  userID INTEGER REFERENCES "User" (id) ON DELETE CASCADE ,
  threadID INTEGER REFERENCES Thread (id) ON DELETE CASCADE,
  voice INTEGER,
  UNIQUE (userID, threadID)
);

CREATE TABLE IF NOT EXISTS Post (
  id SERIAL PRIMARY KEY,
  parent INTEGER DEFAULT 0,
  author CITEXT COLLATE "ucs_basic" REFERENCES "User" (nickname) ON DELETE CASCADE ,
  message VARCHAR,
  isEdited BOOLEAN DEFAULT FALSE,
  forum CITEXT REFERENCES Forum (slug) ON DELETE CASCADE ,
  thread INTEGER REFERENCES Thread (id) ON DELETE CASCADE ,
  created TIMESTAMP DEFAULT now()
);
